-- CreateTable
CREATE TABLE "Restaurent" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "addressOne" STRING NOT NULL,
    "addressTwo" STRING,
    "addressThree" STRING NOT NULL,
    "postalCode" INT8 NOT NULL,
    "imgUrl" STRING NOT NULL DEFAULT 'https://ibb.co/vVps2Xf',
    "aboutUs" STRING NOT NULL,
    "contactUs" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Restaurent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Branchs" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "restaurentId" INT8 NOT NULL,
    "location" STRING,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Branchs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FoodItem" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "restaurentId" INT8 NOT NULL,
    "name" STRING NOT NULL,
    "categoryId" INT8 NOT NULL,
    "imageUrl" STRING NOT NULL DEFAULT 'https://ibb.co/hCF19zC',
    "priceTag" JSONB,
    "priceDefault" DECIMAL(65,30) NOT NULL DEFAULT 2000.00,
    "minimumTime" INT4 NOT NULL,
    "maximumTime" INT4 NOT NULL,
    "rating" INT2,
    "history" INT4 NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FoodItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Category" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Branchs" ADD CONSTRAINT "Branchs_restaurentId_fkey" FOREIGN KEY ("restaurentId") REFERENCES "Restaurent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FoodItem" ADD CONSTRAINT "FoodItem_restaurentId_fkey" FOREIGN KEY ("restaurentId") REFERENCES "Restaurent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FoodItem" ADD CONSTRAINT "FoodItem_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
